# Generated by Django 4.2.7 on 2024-06-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tour_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='countries',
            field=models.CharField(choices=[('southafrica', 'south'), ('norway', 'nor'), ('russia', 'ru'), ('thailand', 'thai')], default='', max_length=20),
        ),
    ]
